# ┌─────────────────────────────────────────────────────────────────────────────────────────+
# │ [ ButterSaveTicket 콘피그 파일입니다. ]
# │ [ 불필요한 메시지는 지우거나 해당 라인 앞에 '#'을 붇여서 주석 처리해주세요. ]
# │
# │ - ButterPL 디스코드 : https://discord.gg/V83PSCQ5ZS
# └─────────────────────────────────────────────────────────────────────────────────────────+

cooldown:
  cooltime: 5 # 쿨타임 시간 (초 단위)
ticket:
  material: PAPER
  display-name: "&f귀환서"
  custom-model-data: 0
  lore:
    - "&7손에 아이템을 들고 우클릭 시 사용됩니다."
location: null
